### Updates an existing patient entity
PUT http://localhost:4000/patients/00b5543b-9151-43c8-8d32-e8d28d358d55
Content-Type: application/json

{
 "name": "Shanmugham S",
  "email": "shanmughams@as.com",
  "address": "12 cs st",
  "dateOfBirth": "2002-11-28",
  "registeredDate": "2025-11-18"
}


###